name: pkkl
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.0
  month_picker_dialog: ^2.0.2
  shared_preferences: ^2.2.0
  encrypt: ^5.0.1
  dio: ^5.2.1+1
  collection: ^1.17.1
  fl_chart: ^0.63.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-100.ttf
          weight: 100
        - asset: assets/fonts/Poppins-200.ttf
          weight: 200
        - asset: assets/fonts/Poppins-300.ttf
          weight: 300
        - asset: assets/fonts/Poppins-400.ttf
          weight: 400
        - asset: assets/fonts/Poppins-500.ttf
          weight: 500
        - asset: assets/fonts/Poppins-600.ttf
          weight: 600
        - asset: assets/fonts/Poppins-700.ttf
          weight: 700
        - asset: assets/fonts/Poppins-800.ttf
          weight: 800
        - asset: assets/fonts/Poppins-900.ttf
          weight: 900

flutter_icons:
  android: true
  image_path_android: assets/images/medan.png

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/images/medan.png